channel_sources:
  - conda-forge/label/rust_dev,conda-forge
channel_targets:
  - conda-forge main
rust_compiler_version:
  - 1.76.0
c_compiler:
  - clang  # [win]
c_compiler_version:
  - 17  # [win]
MACOSX_DEPLOYMENT_TARGET:
  - 10.12  # [osx and x86_64]